[template]
cargo_generate_version = ">=0.16.0"

[hooks]
pre = ["pre-check.rhai"]
post = ["final-msg.rhai"]

[placeholders]
gh_username = { type = "string", prompt = "Github Username?", regex="\\w+" }
camera = { type = "string", prompt = "Camera type?", choices = [
    "2D",
    "3D",
], default = "2D" }

[conditional.'within_cargo_project == false'.placeholders]
ide = { type = "string", prompt = "Which IDE to use?", default = "vscode", choices = ["none", "vscode"] }

[conditional.'within_cargo_project']
ignore = [
    ".github",
    ".vscode",
    ".gitignore",
]

[conditional.'within_cargo_project && is_init']
ignore = ["README.md", "Cargo.toml"]

[conditional.'within_cargo_project == false && ide != "vscode"']
ignore = [".vscode"]
