[template]
cargo_generate_version = ">0.14.0"

[placeholders]

[hooks]
post = ["final-msg.rhai"]

[conditional.'crate_type == "lib"']
ignore = ["src/main.rs", "assets"]

[conditional.'crate_type != "lib"']
ignore = ["src/lib.rs", "tests"]

[conditional.'crate_type != "lib"'.placeholders]
camera = { type = "string", prompt = "Camera type?", choices = [
    "2D",
    "3D",
    "None",
], default = "2D" }

[conditional.'camera != "3D"']
ignore = ["assets/cube.glb"]

[conditional.'within_cargo_project != true'.placeholders]
github_setup = { type = "bool", prompt = "Include GitHub additional files?", default=false }

[conditional.within_cargo_project]
ignore = [
    ".github",
    ".vscode",
    ".gitignore",
    "CHANGELOG.md",
    "CODE_OF_CONDUCT.md",
    "CONTRIBUTING.md",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]
